using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;
using Unity.Netcode;
using Unity.Netcode.Components;
namespace DoNotTouch.Editor {
 public static class Night01Builder {
  public const string Path="Assets/DoNotTouch/Scenes/DoNotTouch_Night01.unity";
  const string Root="Assets/DoNotTouch", Mats=Root+"/Materials/Horror";
  static Transform generated;
  static Material plaster,concrete,wood,oldWood,metal,stone,brass,glass,bulb,text;
  static List<HorrorLamp> lamps;
  static readonly Dictionary<string,int> itemSerials=new();
  static readonly Dictionary<string,string> RoomNames=new(){["STAFF ROOM"]="КОМНАТА ПЕРСОНАЛА",["LOADING / RECEIVING"]="ПРИЁМКА",["SERVICE CORRIDOR"]="СЛУЖЕБНЫЙ КОРИДОР",["SECURITY"]="ОХРАНА",["STORAGE"]="СКЛАД",["ELECTRICAL"]="ЭЛЕКТРОЩИТОВАЯ",["MAIN HALL"]="ГЛАВНЫЙ ЗАЛ",["GALLERY A"]="ГАЛЕРЕЯ A",["GALLERY B"]="ГАЛЕРЕЯ B",["ANCIENT WING"]="АРХЕОЛОГИЯ",["ARCHIVE / RESTRICTED"]="АРХИВ"};
  struct RoomSpec {public string name;public Vector2 center,size;public int id;public bool service,north,south,east,west;public RoomSpec(string n,float x,float z,float w,float d,int i,bool s=false,bool no=false,bool so=false,bool e=false,bool we=false){name=n;center=new(x,z);size=new(w,d);id=i;service=s;north=no;south=so;east=e;west=we;}}
  static readonly RoomSpec[] Rooms={
   new("STAFF ROOM",-27,-18,10,10,0,false,true,false,true,false),new("LOADING / RECEIVING",-14,-18,14,10,1,true,false,false,true,true),new("SERVICE CORRIDOR",5,-18,22,10,2,true,true,false,true,true),new("SECURITY",25,-18,16,10,3,true,true,false,false,true),
   new("STORAGE",-27,0,10,24,4,true,false,true,false,false),new("ELECTRICAL",-14,0,14,24,5,true,false,false,true,false),new("MAIN HALL",5,0,22,24,6,false,true,true,true,true),new("GALLERY A",25,0,16,24,7,false,false,true,false,true),
   new("GALLERY B",5,18,22,10,8,false,false,true,false,true),new("ANCIENT WING",-14,18,14,10,9,false,false,false,true,true),new("ARCHIVE / RESTRICTED",-27,18,10,10,10,true,false,false,true,false)
  };
  [MenuItem("Tools/Do Not Touch/Build Night 01")]
  public static void Build(){if(File.Exists(Path)){Open();Validate();return;}Generate();}
  [MenuItem("Tools/Do Not Touch/Rebuild Night 01")]
  public static void Rebuild(){if(!Application.isBatchMode&&!EditorUtility.DisplayDialog("Rebuild Night 01?","This replaces only DoNotTouch_Night01 and its generated Night 01 data. PrototypeMuseum_Horror remains unchanged.","Rebuild","Cancel"))return;Generate();}
  [MenuItem("Tools/Do Not Touch/Open Night 01")]
  public static void Open(){if(!File.Exists(Path)){Generate();return;}if(!Application.isBatchMode&&!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())return;EditorSceneManager.OpenScene(Path);}
  static void Generate(){
   if(!Application.isBatchMode&&!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())return;
   if(!File.Exists(HorrorBuilder.Path))HorrorBuilder.Build();
   EditorSceneManager.OpenScene(HorrorBuilder.Path);EditorSceneManager.SaveScene(SceneManager.GetActiveScene(),Path);
   var keep=new HashSet<string>{"NetworkManager","Night Shift","Prototype UI","Lobby Camera","EventSystem"};
   foreach(var root in SceneManager.GetActiveScene().GetRootGameObjects())if(!keep.Contains(root.name))UnityEngine.Object.DestroyImmediate(root);
   itemSerials.Clear();generated=new GameObject("Night 01 — generated").transform;Materials();lamps=new();
   var shift=UnityEngine.Object.FindFirstObjectByType<ShiftManager>();var manager=UnityEngine.Object.FindFirstObjectByType<NetworkManager>();
   var definition=AssetDatabase.LoadAssetAtPath<ShiftDefinition>(Root+"/ScriptableObjects/Night01.asset");if(!definition){definition=ScriptableObject.CreateInstance<ShiftDefinition>();AssetDatabase.CreateAsset(definition,Root+"/ScriptableObjects/Night01.asset");}
   definition.durationSeconds=1200;definition.crateTarget=6;definition.inspectionTarget=5;definition.statueTarget=1;EditorUtility.SetDirty(definition);shift.definition=definition;
   foreach(var child in shift.spawnPoints??Array.Empty<Transform>())if(child)UnityEngine.Object.DestroyImmediate(child.gameObject);
   shift.spawnPoints=new[]{new Vector3(-27,1,-20),new Vector3(-24.5f,1,-20),new Vector3(-27,1,-17),new Vector3(-24.5f,1,-17)}.Select((p,i)=>{var t=new GameObject("Night 01 spawn "+(i+1)).transform;t.position=p;t.SetParent(generated);return t;}).ToArray();
   Box("Night 01 structural floor",new Vector3(0,-.24f,1),new Vector3(68,.48f,50),concrete,true);
   Box("North perimeter",new Vector3(0,2.2f,26),new Vector3(68,4.4f,.35f),plaster,true);Box("South perimeter",new Vector3(0,2.2f,-24),new Vector3(68,4.4f,.35f),plaster,true);
   Box("West perimeter",new Vector3(-34,2.2f,1),new Vector3(.35f,4.4f,50),plaster,true);Box("East perimeter",new Vector3(34,2.2f,1),new Vector3(.35f,4.4f,50),plaster,true);
   foreach(var room in Rooms)MakeRoom(room);Wayfinding();
   var directorRoot=new GameObject("Night 01 director");directorRoot.AddComponent<NetworkObject>();var director=directorRoot.AddComponent<NightShiftDirector>();
   var horror=directorRoot.AddComponent<HorrorDirector>();var ambience=directorRoot.AddComponent<MuseumAmbience>();horror.ambience=ambience;director.horror=horror;
   ambience.roomSources=Rooms.Select(r=>{var t=new GameObject(r.name+" audio origin").transform;t.SetParent(generated);t.position=new Vector3(r.center.x,2.4f,r.center.y);return t;}).ToArray();
   for(int i=0;i<Rooms.Length;i++)RoomLamp(Rooms[i]);horror.lamps=lamps.ToArray();
   var registry=Registry();
   var galleryAEntry=new GameObject("Gallery A objective entrance").transform;galleryAEntry.SetParent(generated);galleryAEntry.position=new Vector3(17.5f,1,0);var galleryBEntry=new GameObject("Gallery B objective entrance").transform;galleryBEntry.SetParent(generated);galleryBEntry.position=new Vector3(5,1,13.8f);
   var shipments=new List<NightObjectiveZone>{NightZone("A-01 DESTINATION",new Vector3(21,1,-5),new Vector3(2.2f,2,3),"crate_a",expected:"A-01"),NightZone("A-02 DESTINATION",new Vector3(24,1,-5),new Vector3(2.2f,2,3),"crate_a",expected:"A-02"),NightZone("A-03 DESTINATION",new Vector3(27,1,-5),new Vector3(2.2f,2,3),"crate_a",expected:"A-03"),NightZone("B-01 DESTINATION",new Vector3(-2,1,15),new Vector3(2.2f,2,3),"crate_b",expected:"B-01"),NightZone("B-02 DESTINATION",new Vector3(2,1,15),new Vector3(2.2f,2,3),"crate_b",expected:"B-02"),NightZone("B-03 DESTINATION",new Vector3(6,1,15),new Vector3(2.2f,2,3),"crate_b",expected:"B-03")};
   foreach(var shipment in shipments){bool galleryA=shipment.requiredKind=="crate_a";shipment.waypoint.target=galleryA?galleryAEntry:galleryBEntry;shipment.waypoint.displayName=galleryA?"ГАЛЕРЕЯ A":"ГАЛЕРЕЯ B";shipment.waypoint.roomCenter=galleryA?new Vector2(25,0):new Vector2(5,18);shipment.waypoint.roomSize=galleryA?new Vector2(16,24):new Vector2(22,10);}director.shipmentZones=shipments.ToArray();
   for(int i=0;i<6;i++)Pickup("Shipment crate "+(i+1),new Vector3(-19+i*2.1f,.55f,-18),i<3?new Vector3(.8f,.8f,.8f):new Vector3(1.2f,.6f,.8f),i<3?"crate_a":"crate_b",i<3?oldWood:metal,8,false);
   director.placementZones=new[]{NightZone("PAINTING PLACEMENT",new Vector3(22,1,4),new Vector3(2.4f,2,2.4f),"placement_a",true),NightZone("ARCHAEOLOGY PLACEMENT",new Vector3(-17,1,18),new Vector3(2.4f,2,2.4f),"placement_b",true),NightZone("HALL PLACEMENT",new Vector3(8,1,5),new Vector3(2.4f,2,2.4f),"placement_c",true)};
   Pickup("Framed canvas",new Vector3(-18,.65f,-20),new Vector3(1.1f,1.1f,.3f),"placement_a",oldWood,6,false);Pickup("Catalogued urn",new Vector3(-14,.65f,-20),new Vector3(.65f,1,.65f),"placement_b",stone,7,false);Pickup("Bronze study",new Vector3(-9,.65f,-20),new Vector3(.6f,1.1f,.6f),"placement_c",brass,9,false);
   MakeDisplays(registry,shift);
   var scanner=NetworkBox("Handheld inventory scanner",new Vector3(-27,.9f,-16),new Vector3(.35f,.15f,.65f),metal);scanner.AddComponent<InventoryScanner>();Box("Scanner desk",new Vector3(-27,.36f,-16),new Vector3(1.6f,.72f,1),oldWood,true);Sign("СКАНЕР / [E]",new Vector3(-27,1.2f,-16),Quaternion.identity,.028f);
   PowerGameplay(director);UtilityGameplay(director,registry);Sign("ПРЕДОХРАНИТЕЛЬ",new Vector3(-12,2.1f,-2.76f),Quaternion.identity,.025f);Sign("РУБИЛЬНИК B",new Vector3(-10,2.5f,-2.78f),Quaternion.identity,.03f);director.anomalies=MakeAnomalies();
   director.sculptureZone=NightZone("GALLERY B SCULPTURE",new Vector3(11,1,15),new Vector3(3,2,3),"missing_sculpture");shift.statueZone=LegacyZone("Night statue bridge",director.sculptureZone.transform.position,new Vector3(3,2,3),"missing_sculpture");
   Pickup("Missing marble sculpture",new Vector3(-13,.8f,15),new Vector3(.7f,1.4f,.7f),"missing_sculpture",stone,16,true);
   director.archiveReturnZone=NightZone("ARCHIVE RETURN",new Vector3(-23,1,18),new Vector3(3,2,3),"archive_artifact");director.archiveReturnZone.accessDoor=director.restrictedDoor;director.archiveReturnZone.requiredUnlockPhase=(int)NightPhase.RestrictedArea;
   var artifact=Pickup("Restricted funerary mask",new Vector3(-29,.65f,18),new Vector3(.65f,1,.35f),"archive_artifact",stone,6,false);var record=artifact.AddComponent<ScannableExhibit>();record.exhibitId="1108";record.registry=registry;record.archiveObjective=true;
   director.finalReturnZone=NightZone("FINAL SECURE CART",new Vector3(-10,1,-18),new Vector3(4,2,3),"final_object",false,false,false,true);
   Pickup("Heavy stone tablet",new Vector3(-26,.55f,-7),new Vector3(1.3f,.35f,.9f),"final_object",stone,45,true);Pickup("Sealed collection crate",new Vector3(-21,.65f,-7),new Vector3(1,1,1),"final_object",oldWood,12,false);
   shift.crateZone=LegacyZone("Night shipment bridge",shipments[0].transform.position,new Vector3(2.2f,2,3),"crate_a");
   shift.exitZone=LegacyZone("STAFF EXIT",new Vector3(-25.5f,1,-18.5f),new Vector3(8,2,7),"exit");ZoneOutline(shift.exitZone.transform.position,new Vector3(8,0,7),"ВЫХОД / ПЕРСОНАЛ");
   MakeCart();var watcher=MakeWatcher(director);horror.watcher=watcher;director.watcher=watcher;
   director.recoveryPoints=new[]{new Vector3(-25,1,-18),new Vector3(25,1,-18),new Vector3(-23,1,-5),new Vector3(-11,1,-6)}.Select((p,i)=>{var t=new GameObject("Watcher recovery "+i).transform;t.position=p;t.SetParent(generated);return t;}).ToArray();
   foreach(var zone in UnityEngine.Object.FindObjectsByType<NightObjectiveZone>(FindObjectsSortMode.None))if(zone.plaque)zone.plaque.text=!string.IsNullOrEmpty(zone.expectedExhibitId)?$"МЕСТО {zone.expectedExhibitId}\n{zone.label.ToUpperInvariant()}":zone.label+"\n"+string.Join(" · ",UnityEngine.Object.FindObjectsByType<ExhibitIdentity>(FindObjectsSortMode.None).Where(i=>i.destinationId==zone.destinationId).Select(i=>i.exhibitId).OrderBy(i=>i));
   Volume();var ui=UnityEngine.Object.FindFirstObjectByType<PrototypeUI>();ui.lobbyCamera.transform.SetPositionAndRotation(new Vector3(5,2,3),Quaternion.Euler(4,-25,0));ui.lobbyCamera.GetUniversalAdditionalCameraData().renderPostProcessing=true;
   manager.NetworkConfig.PlayerPrefab=AssetDatabase.LoadAssetAtPath<GameObject>(Root+"/Prefabs/HorrorPlayer.prefab");EnsurePlayerFlashlight(manager);
   RenderSettings.ambientMode=AmbientMode.Flat;RenderSettings.ambientLight=new Color(.09f,.10f,.12f);RenderSettings.ambientIntensity=.55f;RenderSettings.fog=true;RenderSettings.fogMode=FogMode.ExponentialSquared;RenderSettings.fogDensity=.013f;RenderSettings.fogColor=new Color(.026f,.034f,.045f);RenderSettings.skybox=null;
   EditorSceneManager.SaveScene(SceneManager.GetActiveScene(),Path);PrototypeBuilder.FinalizeNetworkAssets();
   var scenes=EditorBuildSettings.scenes.Where(s=>s.path!=Path).ToList();scenes.Insert(0,new EditorBuildSettingsScene(Path,true));EditorBuildSettings.scenes=scenes.ToArray();AssetDatabase.SaveAssets();Validate();Debug.Log("NIGHT 01 BUILD PASSED");
  }
  static void Materials(){plaster=Mat("Cold plaster");concrete=Mat("Service concrete");wood=Mat("Museum oak");oldWood=Mat("Old timber");metal=Mat("Patinated metal");stone=Mat("Carved limestone");brass=Mat("Aged brass");glass=Mat("Display glass");bulb=Mat("Aged diffuser");text=Mat("World typography");}
  static Material Mat(string name)=>AssetDatabase.LoadAssetAtPath<Material>(Mats+"/"+name+".mat");
  static Material NightMat(string name,Color color){string path=Root+"/Materials/Night01 "+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(!m){m=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(m,path);}m.SetColor("_BaseColor",color);EditorUtility.SetDirty(m);return m;}
  static GameObject Box(string name,Vector3 p,Vector3 s,Material m,bool collider=false){var go=GameObject.CreatePrimitive(PrimitiveType.Cube);go.name=name;go.transform.SetParent(generated);go.transform.position=p;go.transform.localScale=s;go.GetComponent<Renderer>().sharedMaterial=m;if(!collider)UnityEngine.Object.DestroyImmediate(go.GetComponent<Collider>());return go;}
  static void FloorStrip(string name,Vector3 p,Vector3 s)=>Box(name,p,s,concrete,false);
  static void MakeRoom(RoomSpec r){
   Vector3 c=new(r.center.x,0,r.center.y);Box(r.name+" floor",c+Vector3.up*.012f,new Vector3(r.size.x,.024f,r.size.y),r.service?concrete:wood);Box(r.name+" ceiling",c+Vector3.up*4.2f,new Vector3(r.size.x,.25f,r.size.y),plaster);
   Wall(r.name+" north",c+Vector3.forward*r.size.y*.5f,r.size.x,0,r.service,r.north);Wall(r.name+" south",c-Vector3.forward*r.size.y*.5f,r.size.x,0,r.service,r.south);Wall(r.name+" east",c+Vector3.right*r.size.x*.5f,r.size.y,90,r.service,r.east);Wall(r.name+" west",c-Vector3.right*r.size.x*.5f,r.size.y,90,r.service,r.west);
   Sign(RoomNames[r.name],c+new Vector3(0,3.5f,-r.size.y*.5f+.16f),Quaternion.Euler(0,180,0),.04f);Sign(RoomNames[r.name],c+new Vector3(0,3.5f,-r.size.y*.5f-.16f),Quaternion.identity,.04f);
   for(float x=-r.size.x*.35f;x<=r.size.x*.35f;x+=Mathf.Max(4,r.size.x*.35f))Box("Ceiling beam",c+new Vector3(x,4,0),new Vector3(.2f,.25f,r.size.y*.92f),r.service?metal:oldWood);
   Furnish(r,c);
   if(r.id==7){foreach(float x in new[]{-3f,3f}){var p=c+new Vector3(x,2.3f,r.size.y*.48f-.08f);Box("Canvas artwork",p,new Vector3(1.65f,1.65f,.025f),NightMat("Ochre canvas",new Color(.34f,.19f,.075f)));Lamp(r.id,p+new Vector3(0,1.3f,-2),p,3,new Color(1,.72f,.4f),false);}}
   if(r.id==8){foreach(float x in new[]{-3f,3f}){var statue=GameObject.CreatePrimitive(PrimitiveType.Capsule);statue.name="Gallery B sculpture";statue.transform.SetParent(generated);statue.transform.position=c+new Vector3(x,1.5f,2);statue.transform.localScale=new Vector3(.5f,.6f,.4f);statue.GetComponent<Renderer>().sharedMaterial=stone;UnityEngine.Object.DestroyImmediate(statue.GetComponent<Collider>());}}
   if(r.id==3)for(int i=-1;i<=1;i++){Box("Security monitor screen",c+new Vector3(i*.85f,1.35f,1.94f),new Vector3(.68f,.42f,.025f),NightMat("Monitor glass",new Color(.09f,.3f,.32f)));Sign("0"+(i+1),c+new Vector3(i*.85f,1.35f,1.92f),Quaternion.identity,.02f);}
   if(r.id==10){Box("Archive wood panel",c+new Vector3(0,1.7f,6.8f),new Vector3(11,3.4f,.15f),oldWood);}
  }
  static void Wall(string name,Vector3 center,float length,float yaw,bool service,bool opening){var root=new GameObject(name);root.transform.SetParent(generated);root.transform.position=center;var q=Quaternion.Euler(0,yaw,0);if(!opening){var solid=Box("Solid wall",center+Vector3.up*2,new Vector3(length,4,.25f),service?concrete:plaster,true);solid.transform.rotation=q;solid.transform.SetParent(root.transform,true);return;}float side=(length-3)/2;foreach(float sign in new[]{-1f,1f}){var p=Box("Room wall",center+Vector3.up*2+q*Vector3.right*sign*(1.5f+side*.5f),new Vector3(side,4,.25f),service?concrete:plaster,true);p.transform.rotation=q;p.transform.SetParent(root.transform,true);}var lintel=Box("Door lintel",center+Vector3.up*3.5f,new Vector3(3,1,.25f),service?metal:oldWood,true);lintel.transform.rotation=q;lintel.transform.SetParent(root.transform,true);}
  static void Furnish(RoomSpec r,Vector3 c){
   if(r.name.Contains("MAIN")){foreach(float x in new[]{-7f,7f})foreach(float z in new[]{-7f,7f})Column(c+new Vector3(x,0,z));Bench(c+new Vector3(-6,0,0),90);Bench(c+new Vector3(6,0,0),90);}
   if(r.name.Contains("GALLERY")){for(int i=-1;i<=1;i+=2){Box("Gallery pedestal",c+new Vector3(i*3,.45f,2),new Vector3(1.3f,.9f,1.3f),stone,true);Box("Collection frame",c+new Vector3(i*3,2.3f,r.size.y*.48f),new Vector3(2,2,.12f),oldWood);}}
   if(r.name=="STORAGE"){for(int row=0;row<3;row++)for(int side=-1;side<=1;side+=2){var p=c+new Vector3(side*4,0,-4+row*4);var rack=NightMat("Rack steel",new Color(.25f,.28f,.3f));foreach(float y in new[]{.15f,1.15f,2.15f})Box("Rack shelf",p+Vector3.up*y,new Vector3(1,.12f,2.5f),rack,true);foreach(float x in new[]{-.45f,.45f})foreach(float z in new[]{-1.2f,1.2f})Box("Rack upright",p+new Vector3(x,1.2f,z),new Vector3(.1f,2.4f,.1f),rack,true);}}
   if(r.name.Contains("ANCIENT")){for(int i=-1;i<=1;i++){Box("Stone sarcophagus",c+new Vector3(i*4,.55f,1),new Vector3(2.3f,1.1f,1.1f),stone,true);Box("Carved sarcophagus lid",c+new Vector3(i*4,1.16f,1),new Vector3(2.1f,.18f,.95f),brass);}}
   if(r.name=="ELECTRICAL"){for(int i=-1;i<=1;i++)Box("Breaker cabinet",c+new Vector3(i*2.4f,1.6f,3.7f),new Vector3(1.6f,2.4f,.35f),metal,true);}
   if(r.name=="SECURITY"){Box("Security desk",c+new Vector3(0,.55f,2.8f),new Vector3(5,1.1f,1.2f),metal,true);}
   if(r.name.Contains("LOADING")){for(int i=0;i<2;i++)Box("Loading dock bumper",c+new Vector3(-5+i*10,.5f,3.8f),new Vector3(2,1,.5f),metal,true);}
   if(r.name=="SERVICE CORRIDOR"){for(int i=-3;i<=3;i++)Box("Service pipe",c+new Vector3(i*2.2f,3.25f,2.8f),new Vector3(1.6f,.12f,.12f),metal);}
   if(r.name=="STAFF ROOM"){var board=NetworkBox("Task board",c+new Vector3(-3,2.2f,4.72f),new Vector3(4,1.7f,.12f),oldWood);board.AddComponent<NightInteractable>().mode=NightInteraction.ShiftBoard;Sign("НОЧЬ 01\nПРИЁМКА · УЧЁТ · ОХРАНА",c+new Vector3(-3,2.2f,4.62f),Quaternion.identity,.034f);Box("Radio equipment",c+new Vector3(3.8f,.7f,2.8f),new Vector3(1.8f,1.4f,.8f),metal,true);}
  }
  static void Column(Vector3 p){Box("Hall column",p+Vector3.up*2,new Vector3(.65f,4,.65f),stone,true);Box("Column capital",p+Vector3.up*3.9f,new Vector3(.9f,.2f,.9f),stone);}
  static void Bench(Vector3 p,float yaw){var q=Quaternion.Euler(0,yaw,0);var seat=Box("Museum bench",p+Vector3.up*.5f,new Vector3(2.2f,.16f,.55f),oldWood,true);seat.transform.rotation=q;}
  static GameObject Sign(string label,Vector3 p,Quaternion q,float size){var go=new GameObject(label);go.transform.SetParent(generated);go.transform.SetPositionAndRotation(p,q);var tm=go.AddComponent<TextMesh>();tm.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");tm.text=label;tm.fontSize=64;tm.characterSize=size;tm.anchor=TextAnchor.MiddleCenter;tm.alignment=TextAlignment.Center;tm.color=new Color(.48f,.45f,.38f);go.GetComponent<Renderer>().sharedMaterial=text;go.AddComponent<DepthText>().template=text;return go;}
  static void Wayfinding(){Sign("← ПЕРСОНАЛ  ·  СКЛАД ↑  ·  ГЛАВНЫЙ ЗАЛ →",new Vector3(-14,2.8f,-13),Quaternion.identity,.032f);Sign("← АРХЕОЛОГИЯ  ·  ГАЛЕРЕЯ B →",new Vector3(5,2.8f,10),Quaternion.identity,.032f);Sign("ОХРАНА →  ·  ЭЛЕКТРОЩИТОВАЯ ←",new Vector3(8,2.7f,-14),Quaternion.identity,.032f);Sign("АРХИВ / ДОСТУП ПО ПРОПУСКУ",new Vector3(-20,2.8f,15),Quaternion.Euler(0,90,0),.034f);}
  static void RoomLamp(RoomSpec r){Vector3 c=new(r.center.x,3.85f,r.center.y);Color color=r.id==0||r.id==7?new Color(1,.72f,.45f):r.name.Contains("ANCIENT")?new Color(.82f,.62f,.42f):new Color(.62f,.7f,.78f);float main=r.name=="STAFF ROOM"?9:r.name=="STORAGE"?5.5f:7;Lamp(r.id,c,c-Vector3.up*3.4f,main,color,r.id==6||r.id==7||r.id==8);if(r.id!=6)Lamp(r.id,c+Vector3.forward*r.size.y*.22f,c+new Vector3(0,-2,r.size.y*.48f),3,color,false);if(Mathf.Max(r.size.x,r.size.y)>=16){Vector3 axis=r.size.x>=r.size.y?Vector3.right*r.size.x*.28f:Vector3.forward*r.size.y*.28f;Lamp(r.id,c+axis,(c+axis)-Vector3.up*3.3f,5.5f,color,false);Lamp(r.id,c-axis,(c-axis)-Vector3.up*3.3f,5.5f,color,false);}if(r.name=="STORAGE")Lamp(r.id,c+new Vector3(3,0,-3),c+new Vector3(3,-3,-3),3.5f,color,false);if(r.service&&r.id!=0)Lamp(r.id,c+new Vector3(r.size.x*.3f,-.5f,r.size.y*.3f),c+new Vector3(r.size.x*.3f,-3,r.size.y*.3f),1.5f,new Color(.55f,.04f,.025f),false,true);}
  static void Lamp(int room,Vector3 p,Vector3 target,float intensity,Color color,bool shadows,bool emergency=false){var housing=Box("Night fixture",p,new Vector3(.7f,.16f,.35f),metal);var diffuser=Box("Night diffuser",p-Vector3.up*.1f,new Vector3(.58f,.035f,.25f),bulb);var light=new GameObject("Night spotlight").AddComponent<Light>();light.transform.SetParent(housing.transform);light.transform.position=p-Vector3.up*.18f;light.transform.rotation=Quaternion.LookRotation(target-light.transform.position);light.type=LightType.Spot;light.spotAngle=92;light.innerSpotAngle=52;light.range=12;light.intensity=intensity;light.color=color;light.shadows=shadows?LightShadows.Soft:LightShadows.None;var lamp=housing.AddComponent<HorrorLamp>();lamp.room=room;lamp.source=light;lamp.bulb=diffuser.GetComponent<Renderer>();lamp.intensity=intensity;lamp.emission=color;lamp.emergency=emergency;lamps.Add(lamp);}
  static GameObject NetworkBox(string name,Vector3 p,Vector3 s,Material m){var go=Box(name,p,s,m,true);go.AddComponent<NetworkObject>();return go;}
  static void EnsurePlayerFlashlight(NetworkManager manager){string path=AssetDatabase.GetAssetPath(manager.NetworkConfig.PlayerPrefab);var root=PrefabUtility.LoadPrefabContents(path);var player=root.GetComponent<PlayerController>();player.EnsureFlashlight();PrefabUtility.SaveAsPrefabAsset(root,path);PrefabUtility.UnloadPrefabContents(root);manager.NetworkConfig.PlayerPrefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);}
  static GameObject Pickup(string name,Vector3 p,Vector3 s,string kind,Material m,float mass,bool heavy){var go=NetworkBox(name,p,s,m);var body=go.AddComponent<Rigidbody>();body.mass=mass;body.interpolation=RigidbodyInterpolation.Interpolate;body.collisionDetectionMode=CollisionDetectionMode.ContinuousDynamic;body.angularDamping=1;go.AddComponent<NetworkTransform>();go.AddComponent<NetworkRigidbody>();var pickup=go.AddComponent<PickupObject>();pickup.kind=kind;pickup.heavy=heavy;var identity=go.AddComponent<ExhibitIdentity>();identity.destinationId=kind;itemSerials.TryGetValue(kind,out int serial);itemSerials[kind]=++serial;identity.exhibitId=ExhibitIdentity.Prefix(kind)+"-"+serial.ToString("00");if(kind=="crate_a"||kind=="crate_b"){foreach(float x in new[]{-.32f,.32f}){var band=Box("Shipping band",p+new Vector3(s.x*x,0,-s.z*.51f),new Vector3(.07f,s.y,.035f),kind=="crate_a"?brass:oldWood);band.transform.SetParent(go.transform,true);}string crateLabel=identity.exhibitId+"\n"+ExhibitIdentity.Destination(kind).ToUpperInvariant();var front=Sign(crateLabel,p+new Vector3(0,s.y*.08f,-s.z*.51f),Quaternion.identity,.05f);front.transform.SetParent(go.transform,true);var back=Sign(crateLabel,p+new Vector3(0,s.y*.08f,s.z*.51f),Quaternion.Euler(0,180,0),.05f);back.transform.SetParent(go.transform,true);}else{var plaque=Sign(identity.exhibitId,p+new Vector3(0,s.y*.15f,-s.z*.51f),Quaternion.identity,.032f);plaque.transform.SetParent(go.transform,true);}if(kind.Contains("sculpture")||kind=="placement_b"||kind=="placement_c"||kind=="archive_artifact"){go.GetComponent<MeshRenderer>().enabled=false;var shape=GameObject.CreatePrimitive(kind=="placement_b"?PrimitiveType.Cylinder:PrimitiveType.Capsule);UnityEngine.Object.DestroyImmediate(shape.GetComponent<Collider>());shape.transform.SetParent(go.transform,false);shape.transform.localScale=new Vector3(.8f,.5f,.8f);shape.GetComponent<Renderer>().sharedMaterial=m;}return go;}
  static NightObjectiveZone NightZone(string name,Vector3 p,Vector3 s,string kind,bool placement=false,bool sculpture=false,bool archive=false,bool final=false,string expected=""){var go=new GameObject(name);go.transform.SetParent(generated);go.transform.position=p;var col=go.AddComponent<BoxCollider>();col.isTrigger=true;col.size=s;var zone=go.AddComponent<NightObjectiveZone>();zone.requiredKind=kind;zone.placement=placement;zone.sculpture=sculpture;zone.archiveReturn=archive;zone.finalReturn=final;zone.destinationId=kind;zone.expectedExhibitId=expected;zone.label=ExhibitIdentity.Destination(kind);var marker=new GameObject("Matching destination outline "+(string.IsNullOrEmpty(expected)?ExhibitIdentity.Prefix(kind):expected));marker.transform.SetParent(generated);zone.marker=marker;int before=generated.childCount;ZoneOutline(p,s,"");var edges=new List<Transform>();for(int i=before;i<generated.childCount;i++)edges.Add(generated.GetChild(i));foreach(var edge in edges)edge.SetParent(marker.transform,true);marker.SetActive(false);var waypointObject=new GameObject("Current room waypoint "+name);waypointObject.transform.SetParent(generated);zone.waypoint=waypointObject.AddComponent<ObjectiveWaypoint>();zone.waypoint.zone=zone;Box("Destination plaque",p+new Vector3(0,-.35f,s.z*.5f),new Vector3(2.15f,.7f,.08f),metal);zone.plaque=Sign(string.IsNullOrEmpty(expected)?zone.label+" / "+ExhibitIdentity.Prefix(kind):$"МЕСТО {expected}\n{zone.label.ToUpperInvariant()}",p+new Vector3(0,-.3f,s.z*.5f-.06f),Quaternion.identity,.028f).GetComponent<TextMesh>();return zone;}
  static ObjectiveZone LegacyZone(string name,Vector3 p,Vector3 s,string kind){var go=new GameObject(name);go.transform.SetParent(generated);go.transform.position=p;var col=go.AddComponent<BoxCollider>();col.isTrigger=true;col.size=s;var z=go.AddComponent<ObjectiveZone>();z.requiredKind=kind;return z;}
  static void ZoneOutline(Vector3 p,Vector3 s,string label){foreach(float sign in new[]{-1f,1f}){Box("Zone edge",new Vector3(p.x+sign*s.x*.5f,.025f,p.z),new Vector3(.035f,.02f,s.z),brass);Box("Zone edge",new Vector3(p.x,.025f,p.z+sign*s.z*.5f),new Vector3(s.x,.02f,.035f),brass);}if(!string.IsNullOrEmpty(label))Sign(label,new Vector3(p.x,.045f,p.z),Quaternion.Euler(90,0,0),.032f);}
  static ExhibitRegistry Registry(){string path=Root+"/ScriptableObjects/Night01Registry.asset";var r=AssetDatabase.LoadAssetAtPath<ExhibitRegistry>(path);if(!r){r=ScriptableObject.CreateInstance<ExhibitRegistry>();AssetDatabase.CreateAsset(r,path);}r.entries=new(){new(){id="0241",label="Мраморный этюд",registered=true},new(){id="0713",label="Античный сосуд",registered=true},new(){id="1108",label="Погребальная маска",registered=true},new(){id="4410",label="Неизвестная фигура",registered=false},new(){id="1902",label="Печать коллекции",registered=true}};EditorUtility.SetDirty(r);return r;}
  static void MakeDisplays(ExhibitRegistry registry,ShiftManager shift){var points=new[]{new Vector3(21,.65f,3),new Vector3(27,.65f,3),new Vector3(1,.65f,6),new Vector3(-12,.65f,17),new Vector3(8,.65f,18)};for(int i=0;i<points.Length;i++){var root=NetworkBox("Display case "+(i+1),points[i],new Vector3(1.5f,1.3f,1.1f),metal);root.AddComponent<DisplayCase>();var exhibit=GameObject.CreatePrimitive(i%2==0?PrimitiveType.Sphere:PrimitiveType.Cylinder);exhibit.name="Registered exhibit";exhibit.transform.SetParent(root.transform,false);exhibit.transform.localPosition=new Vector3(0,.85f,0);exhibit.transform.localScale=Vector3.one*.4f;exhibit.GetComponent<Renderer>().sharedMaterial=stone;UnityEngine.Object.DestroyImmediate(exhibit.GetComponent<Collider>());var cover=Box("Display glass",points[i]+Vector3.up*.9f,new Vector3(1.55f,.9f,1.15f),glass);}}
  static void PowerGameplay(NightShiftDirector d){foreach(var p in new[]{new Vector3(-27,.8f,-8),new Vector3(-13,.8f,-9),new Vector3(25,.8f,-20)}){var fuse=NetworkBox("Replacement fuse",p,new Vector3(.18f,.45f,.18f),brass);fuse.AddComponent<NightInteractable>().mode=NightInteraction.FusePickup;}var socket=NetworkBox("Blown fuse socket",new Vector3(-12,1.4f,-2.6f),new Vector3(.7f,.9f,.25f),metal);socket.AddComponent<NightInteractable>().mode=NightInteraction.FuseSocket;var breaker=NetworkBox("Gallery B breaker",new Vector3(-10,1.5f,-2.6f),new Vector3(1.2f,1.6f,.3f),metal);breaker.AddComponent<NightInteractable>().mode=NightInteraction.Breaker;}
  static void UtilityGameplay(NightShiftDirector d,ExhibitRegistry r){var console=NetworkBox("Security camera console",new Vector3(25,1.25f,-15.8f),new Vector3(2.8f,.8f,.5f),metal);console.AddComponent<NightInteractable>().mode=NightInteraction.SecurityConsole;for(int i=0;i<5;i++){var camera=Box("Security camera "+(i+1),new Vector3(-20+i*10,3.4f,i%2==0?8:-12),new Vector3(.45f,.35f,.65f),metal);var node=camera.AddComponent<SecurityCameraNode>();node.feedIndex=i;node.roomName=Rooms[Mathf.Min(i+4,Rooms.Length-1)].name;}var key=NetworkBox("Archive keycard",new Vector3(27,.9f,-16),new Vector3(.5f,.08f,.32f),brass);key.AddComponent<NightInteractable>().mode=NightInteraction.Keycard;var finalCase=NetworkBox("Final display latch",new Vector3(14,.9f,17),new Vector3(.6f,.5f,.25f),metal);finalCase.AddComponent<NightInteractable>().mode=NightInteraction.FinalCase;
   Scannable("Unregistered exhibit",new Vector3(28,.9f,-1),"4410",r,true,false,false);Scannable("Печать коллекции",new Vector3(14,1.4f,17),"1902",r,false,false,true);
   d.restrictedDoor=Door("Restricted archive door",new Vector3(-22,0,18),90,(int)NightPhase.RestrictedArea,"АРХИВ: НУЖНО ЗАДАНИЕ И ПРОПУСК");d.restrictedDoor.Locked.Value=true;Door("Electrical room door",new Vector3(-7,0,0),90,(int)NightPhase.PowerProblem,"ДОСТУП ПРИ АВАРИИ");Door("Staff service door",new Vector3(-22,0,-18),90,0,"ПЕРСОНАЛ");}
  static NightAnomalyProp[] MakeAnomalies(){
   var changed=NetworkBox("Changed portrait anomaly",new Vector3(20,2.2f,8.7f),new Vector3(1.7f,2,.12f),oldWood);var a=changed.AddComponent<NightAnomalyProp>();a.presentation=AnomalyPresentation.ChangedPainting;a.targetRenderer=changed.GetComponent<Renderer>();
   var caseRoot=NetworkBox("Opened display anomaly",new Vector3(2,.7f,-5),new Vector3(1.5f,1.2f,1.1f),metal);var lid=Box("Anomaly glass lid",caseRoot.transform.position+Vector3.up*.85f,new Vector3(1.55f,.06f,1.15f),glass);lid.transform.SetParent(caseRoot.transform,true);var b=caseRoot.AddComponent<NightAnomalyProp>();b.presentation=AnomalyPresentation.OpenCase;b.movingPart=lid.transform;
   var extra=NetworkBox("Extra unlisted exhibit anomaly",new Vector3(-4,.9f,18),new Vector3(.55f,1.4f,.55f),stone);var c=extra.AddComponent<NightAnomalyProp>();c.presentation=AnomalyPresentation.ExtraExhibit;c.targetRenderer=extra.GetComponent<Renderer>();return new[]{a,b,c};
  }
  static void Scannable(string name,Vector3 p,string id,ExhibitRegistry r,bool unknown,bool archive,bool final){var go=NetworkBox(name,p,new Vector3(.65f,1.2f,.65f),stone);var s=go.AddComponent<ScannableExhibit>();s.exhibitId=id;s.registry=r;s.unknownObjective=unknown;s.archiveObjective=archive;s.finalObjective=final;}
  static MuseumDoor Door(string name,Vector3 p,float yaw,int phase,string label){var go=new GameObject(name);go.transform.SetParent(generated);go.transform.SetPositionAndRotation(p,Quaternion.Euler(0,yaw,0));go.AddComponent<NetworkObject>();var door=go.AddComponent<MuseumDoor>();door.unlockPhase=phase;door.accessLabel=label;var pivot=new GameObject("Door pivot").transform;pivot.SetParent(go.transform,false);pivot.localPosition=Vector3.left*1.45f;door.leaf=pivot;var leaf=Box("Door leaf",Vector3.zero,new Vector3(2.9f,2.8f,.16f),oldWood,true);leaf.transform.SetParent(pivot,false);leaf.transform.localPosition=new Vector3(1.45f,1.4f,0);return door;}
  static void MakeCart(){var cart=new GameObject("Museum trolley");cart.transform.SetParent(generated);cart.transform.position=new Vector3(-10,.4f,-16);cart.AddComponent<MuseumCart>();var tray=Box("Trolley tray",cart.transform.position,new Vector3(2.6f,.25f,1.5f),metal,true);tray.transform.SetParent(cart.transform,true);var handle=Box("Trolley handle",cart.transform.position+new Vector3(-1.15f,.6f,0),new Vector3(.12f,1.3f,1.45f),metal);handle.transform.SetParent(cart.transform,true);var body=cart.AddComponent<Rigidbody>();body.mass=38;body.angularDamping=4;body.linearDamping=1.5f;body.constraints=RigidbodyConstraints.FreezeRotationX|RigidbodyConstraints.FreezeRotationZ;cart.AddComponent<NetworkObject>();cart.AddComponent<NetworkTransform>();cart.AddComponent<NetworkRigidbody>();}
  static Watcher MakeWatcher(NightShiftDirector director){var go=new GameObject("The Watcher — Night 01");go.transform.position=new Vector3(5,0,7);go.AddComponent<NetworkObject>();go.AddComponent<NetworkTransform>();var watcher=go.AddComponent<Watcher>();watcher.activationDelay=new Vector2(35,75);watcher.moveCooldown=8;var collider=go.AddComponent<CapsuleCollider>();collider.center=Vector3.up*1.05f;collider.height=2.1f;collider.radius=.33f;void Part(string n,Vector3 p,Vector3 s,PrimitiveType type){var child=GameObject.CreatePrimitive(type);child.name=n;child.transform.SetParent(go.transform,false);child.transform.localPosition=p;child.transform.localScale=s;child.GetComponent<Renderer>().sharedMaterial=stone;UnityEngine.Object.DestroyImmediate(child.GetComponent<Collider>());}Part("Stone torso",new Vector3(0,1.3f,0),new Vector3(.6f,.44f,.34f),PrimitiveType.Capsule);Part("Featureless head",new Vector3(0,1.95f,0),new Vector3(.35f,.4f,.31f),PrimitiveType.Sphere);foreach(float side in new[]{-1f,1f}){Part("Stone leg",new Vector3(side*.16f,.53f,0),new Vector3(.18f,.46f,.21f),PrimitiveType.Cylinder);Part("Stone arm",new Vector3(side*.38f,1.18f,0),new Vector3(.14f,.4f,.15f),PrimitiveType.Cylinder);}UnityEngine.Physics.SyncTransforms();var positions=new List<Vector3>{new Vector3(5,0,7)};for(float x=-31;x<=31;x+=2)for(float z=-21;z<=23;z+=2){var p=new Vector3(x,0,z);if(Vector3.Distance(p,go.transform.position)<1)continue;if(!UnityEngine.Physics.CheckCapsule(p+Vector3.up*.5f,p+Vector3.up*1.85f,.44f,~0,QueryTriggerInteraction.Ignore))positions.Add(p);} watcher.positions=positions.Select((p,i)=>{var t=new GameObject("Watcher navigation anchor "+i).transform;t.position=p;t.SetParent(generated);return t;}).ToArray();return watcher;}
  static void Volume(){var profile=AssetDatabase.LoadAssetAtPath<VolumeProfile>(Root+"/ScriptableObjects/HorrorVolume.asset");var volume=new GameObject("Night 01 Global Volume").AddComponent<Volume>();volume.isGlobal=true;volume.priority=20;volume.sharedProfile=profile;var pipeline=AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(Root+"/ScriptableObjects/HorrorPipeline.asset");new GameObject("Night 01 renderer settings").AddComponent<HorrorRenderSettings>().pipeline=pipeline;}
  static bool RoomContains(string roomName,Vector3 point,float margin=.15f){var room=Rooms.FirstOrDefault(r=>r.name==roomName);return room.name!=null&&Mathf.Abs(point.x-room.center.x)<=room.size.x*.5f-margin&&Mathf.Abs(point.z-room.center.y)<=room.size.y*.5f-margin;}
  static void ValidateObjectiveAccess(List<string> errors,NightObjectiveZone zone,NightPhase activationPhase,string expectedRoom){
   if(!zone){errors.Add("Missing objective destination for "+expectedRoom);return;}
   if(!RoomContains(expectedRoom,zone.transform.position))errors.Add($"{zone.name} is outside its expected reachable room {expectedRoom}");
   if(!zone.DependencyAllowsPhase((int)activationPhase))errors.Add($"{zone.name} activates in {activationPhase} before its access dependency unlocks");
   if(zone.accessDoor&&(zone.requiredUnlockPhase<zone.accessDoor.unlockPhase||!zone.waypoint))errors.Add($"{zone.name} has an invalid door dependency or world marker");
  }
  [MenuItem("Tools/Do Not Touch/Run Night 01 Validation")]
  public static void Validate(){var errors=new List<string>();var d=UnityEngine.Object.FindFirstObjectByType<NightShiftDirector>();if(SceneManager.GetActiveScene().path!=Path)errors.Add("Open DoNotTouch_Night01 before Night 01 validation");if(!d)errors.Add("NightShiftDirector missing");if(Rooms.Any(r=>!GameObject.Find(r.name+" floor")))errors.Add("One or more required rooms missing");if(Rooms.Any(r=>!GameObject.Find(r.name+" ceiling")))errors.Add("One or more room ceilings missing");for(int i=0;i<Rooms.Length;i++)for(int j=i+1;j<Rooms.Length;j++){RoomSpec a=Rooms[i];RoomSpec b=Rooms[j];float overlapX=Mathf.Min(a.center.x+a.size.x*.5f,b.center.x+b.size.x*.5f)-Mathf.Max(a.center.x-a.size.x*.5f,b.center.x-b.size.x*.5f);float overlapZ=Mathf.Min(a.center.y+a.size.y*.5f,b.center.y+b.size.y*.5f)-Mathf.Max(a.center.y-a.size.y*.5f,b.center.y-b.size.y*.5f);if(overlapX>.05f&&overlapZ>.05f)errors.Add("Overlapping room geometry: "+a.name+" / "+b.name);}if(UnityEngine.Object.FindObjectsByType<Watcher>(FindObjectsSortMode.None).FirstOrDefault() is not Watcher w||w.positions.Length<10)errors.Add("Watcher navigation anchors incomplete");if(UnityEngine.Object.FindObjectsByType<NightInteractable>(FindObjectsSortMode.None).Count(i=>i.mode==NightInteraction.FusePickup)<3)errors.Add("Three fuse locations required");if(!AssetDatabase.LoadAssetAtPath<ExhibitRegistry>(Root+"/ScriptableObjects/Night01Registry.asset"))errors.Add("Scanner registry missing");if(!d||!d.restrictedDoor||!d.restrictedDoor.Locked.Value)errors.Add("Restricted door missing or unlocked");if(UnityEngine.Object.FindObjectsByType<SecurityCameraNode>(FindObjectsSortMode.None).Length<5)errors.Add("Five security cameras required");if(!UnityEngine.Object.FindFirstObjectByType<MuseumCart>())errors.Add("Museum cart missing");if(!UnityEngine.Object.FindObjectsByType<PickupObject>(FindObjectsSortMode.None).Any(p=>p.heavy))errors.Add("Heavy exhibit missing");if(!UnityEngine.Object.FindFirstObjectByType<InventoryScanner>())errors.Add("Inventory scanner missing");if(!UnityEngine.Object.FindFirstObjectByType<ShiftManager>().exitZone)errors.Add("Staff exit missing");if(d&&(d.shipmentZones.Length!=6||d.placementZones.Length!=3||!d.sculptureZone||!d.archiveReturnZone||!d.finalReturnZone))errors.Add("Objective chain references incomplete");
   foreach(var room in Rooms){foreach(var side in new[]{"north","south","east","west"}){var wall=GameObject.Find(room.name+" "+side);if(!wall||wall.GetComponentsInChildren<Collider>().Length==0)errors.Add(room.name+" missing wall "+side);}if(!UnityEngine.Object.FindObjectsByType<TextMesh>(FindObjectsSortMode.None).Any(t=>t.text==RoomNames[room.name]))errors.Add("Missing Russian room sign: "+room.name);}
   foreach(var door in UnityEngine.Object.FindObjectsByType<MuseumDoor>(FindObjectsSortMode.None)){bool opening=UnityEngine.Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).Any(t=>t.name=="Door lintel"&&Vector3.Distance(t.position,door.transform.position+Vector3.up*3.5f)<.1f);if(!opening)errors.Add("Door without wall opening: "+door.name);}
   var identities=UnityEngine.Object.FindObjectsByType<ExhibitIdentity>(FindObjectsSortMode.None);var zones=UnityEngine.Object.FindObjectsByType<NightObjectiveZone>(FindObjectsSortMode.None);
   if(identities.Select(i=>i.exhibitId).Distinct().Count()!=identities.Length)errors.Add("Duplicate objective prop ID");
   foreach(var identity in identities){if(string.IsNullOrEmpty(identity.exhibitId)||!identity.GetComponentsInChildren<TextMesh>().Any(t=>t.text.Contains(identity.exhibitId)))errors.Add("Indistinguishable object ID: "+identity.name);if(!zones.Any(z=>z.Accepts(identity.GetComponent<PickupObject>())))errors.Add("Missing destination: "+identity.exhibitId);}
   var objectiveCrates=identities.Where(i=>i.destinationId=="crate_a"||i.destinationId=="crate_b").ToArray();var shipmentZones=d?d.shipmentZones:Array.Empty<NightObjectiveZone>();
   if(objectiveCrates.Length!=6||objectiveCrates.Any(i=>!i.GetComponentsInChildren<TextMesh>().Any(t=>t.text.Contains(i.exhibitId)&&t.text.Contains(ExhibitIdentity.Destination(i.destinationId).ToUpperInvariant()))))errors.Add("Every objective crate needs a large ID and destination label");
   if(shipmentZones.Any(z=>string.IsNullOrEmpty(z.expectedExhibitId)||!z.plaque||!z.plaque.text.Contains(z.expectedExhibitId)||!z.waypoint||!z.waypoint.target||z.waypoint.roomSize.x<=0))errors.Add("Shipment destination ID or room waypoint missing");
   foreach(var crate in objectiveCrates)if(shipmentZones.Count(z=>z.expectedExhibitId==crate.exhibitId&&z.Accepts(crate.GetComponent<PickupObject>()))!=1)errors.Add("Objective crate must have exactly one matching destination: "+crate.exhibitId);
   if(d){foreach(var zone in d.shipmentZones)ValidateObjectiveAccess(errors,zone,NightPhase.NormalShift,zone.requiredKind=="crate_a"?"GALLERY A":"GALLERY B");if(d.placementZones.Length==3){ValidateObjectiveAccess(errors,d.placementZones.FirstOrDefault(z=>z.requiredKind=="placement_a"),NightPhase.NormalShift,"GALLERY A");ValidateObjectiveAccess(errors,d.placementZones.FirstOrDefault(z=>z.requiredKind=="placement_b"),NightPhase.NormalShift,"ANCIENT WING");ValidateObjectiveAccess(errors,d.placementZones.FirstOrDefault(z=>z.requiredKind=="placement_c"),NightPhase.NormalShift,"MAIN HALL");}ValidateObjectiveAccess(errors,d.sculptureZone,NightPhase.WatcherActive,"GALLERY B");ValidateObjectiveAccess(errors,d.archiveReturnZone,NightPhase.RestrictedArea,"ARCHIVE / RESTRICTED");ValidateObjectiveAccess(errors,d.finalReturnZone,NightPhase.FinalTask,"LOADING / RECEIVING");if(d.archiveReturnZone&&(d.archiveReturnZone.accessDoor!=d.restrictedDoor||d.archiveReturnZone.requiredUnlockPhase!=(int)NightPhase.RestrictedArea||d.restrictedDoor.unlockPhase!=(int)NightPhase.RestrictedArea))errors.Add("Archive objective access dependency is incomplete");}
   if(d&&d.CurrentShipmentZone()&&string.IsNullOrEmpty(d.CurrentShipmentZone().label))errors.Add("Current objective has no destination");
   var playerPrefab=UnityEngine.Object.FindFirstObjectByType<NetworkManager>()?.NetworkConfig.PlayerPrefab;var player=playerPrefab?playerPrefab.GetComponent<PlayerController>():null;if(!player||!player.flashlight)errors.Add("Player flashlight missing");
   if(NightRules.StateForPhase(NightPhase.FirstAnomalies)!=WatcherState.Awake)errors.Add("Watcher cannot leave Dormant");
   if(d&&!d.ObjectiveText(UnityEngine.Object.FindFirstObjectByType<ShiftManager>()).Contains("ТЕКУЩАЯ ЗАДАЧА"))errors.Add("Missing Russian objective");
   PrototypeBuilder.Validate();if(errors.Count>0){foreach(var e in errors)Debug.LogError("NIGHT 01: "+e);throw new InvalidOperationException("Night 01 validation failed: "+errors.Count);}Debug.Log("NIGHT 01 VALIDATION PASSED: walls, door openings, unique IDs, reachable destinations, access dependencies, Russian signs, Watcher phases and references.");}
  public static void BuildMac(){Build();var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Path},locationPathName="Builds/macOS/DoNotTouch_Night01.app",target=BuildTarget.StandaloneOSX,options=BuildOptions.Development});if(report.summary.result!=UnityEditor.Build.Reporting.BuildResult.Succeeded)throw new Exception("Night 01 macOS build failed");}
  public static void RebuildMac(){Rebuild();BuildMac();}
 }
}
