using System.Collections;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using Unity.Netcode;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
namespace DoNotTouch.Tests {
 public class Night01PlayTests {
  NetworkManager manager;PlayerController player;NightShiftDirector director;ShiftManager shift;
  [UnitySetUp] public IEnumerator StartNight(){yield return SceneManager.LoadSceneAsync("DoNotTouch_Night01",LoadSceneMode.Single);manager=Object.FindFirstObjectByType<NetworkManager>();Assert.IsTrue(manager.StartHost());for(int i=0;i<90&&!PlayerController.Local;i++)yield return null;player=PlayerController.Local;director=NightShiftDirector.Instance;shift=ShiftManager.Instance;Assert.IsNotNull(player);Assert.IsNotNull(director);player.SetPause(true);yield return new WaitForFixedUpdate();}
  [UnityTearDown] public IEnumerator StopNight(){if(manager){manager.Shutdown();yield return null;Object.Destroy(manager.gameObject);}yield return null;}
  void Place(Vector3 point,Quaternion rotation){var body=player.GetComponent<Rigidbody>();body.constraints=RigidbodyConstraints.FreezeAll;body.position=point;player.transform.SetPositionAndRotation(point,rotation);player.DebugAim(rotation.eulerAngles.y);Physics.SyncTransforms();}
  bool HasPhysicalRoute(Vector3 start,Vector3 destination){
   var disabled=PickupObject.Active.Where(p=>p).SelectMany(p=>p.GetComponentsInChildren<Collider>()).Where(c=>c.enabled).ToArray();foreach(var collider in disabled)collider.enabled=false;Physics.SyncTransforms();
   try{
    const float step=1f,radius=.28f;const int minX=-32,maxX=32,minZ=-22,maxZ=24;int mask=~(1<<8);
    Vector2Int Cell(Vector3 p)=>new(Mathf.RoundToInt(p.x),Mathf.RoundToInt(p.z));Vector3 Point(Vector2Int c)=>new(c.x,.95f,c.y);
    bool Clear(Vector2Int c){var p=Point(c);return !Physics.CheckCapsule(p+Vector3.down*.6f,p+Vector3.up*.7f,radius,mask,QueryTriggerInteraction.Ignore);}
    var from=Cell(start);var goal=Cell(destination);var open=new Queue<Vector2Int>();var visited=new HashSet<Vector2Int>{from};open.Enqueue(from);var directions=new[]{Vector2Int.right,Vector2Int.left,Vector2Int.up,Vector2Int.down};
    while(open.Count>0){var cell=open.Dequeue();if(Vector2Int.Distance(cell,goal)<=1.1f)return true;foreach(var direction in directions){var next=cell+direction;if(next.x<minX||next.x>maxX||next.y<minZ||next.y>maxZ||visited.Contains(next)||!Clear(next))continue;var p=Point(cell);var delta=Point(next)-p;if(Physics.CapsuleCast(p+Vector3.down*.6f,p+Vector3.up*.7f,radius,delta.normalized,step,mask,QueryTriggerInteraction.Ignore))continue;visited.Add(next);open.Enqueue(next);}}
    return false;
   }finally{foreach(var collider in disabled)if(collider)collider.enabled=true;Physics.SyncTransforms();}
  }
  [UnityTest] public IEnumerator ExitCannotCompleteBeforeMandatoryTasks(){Place(shift.exitZone.transform.position,Quaternion.identity);yield return new WaitForSeconds(.35f);Assert.AreEqual(0,shift.Result.Value);Assert.AreEqual((int)NightPhase.NormalShift,director.Phase.Value);}
  [UnityTest] public IEnumerator ExitCompletesOnlyAfterEscapeUnlock(){director.ForcePhaseForTests(NightPhase.Escape);Place(shift.exitZone.transform.position,Quaternion.identity);yield return new WaitForSeconds(.35f);Assert.AreEqual(1,shift.Result.Value);}
  [UnityTest] public IEnumerator FuseSocketBreakerRestoresSynchronizedPower(){director.ForcePhaseForTests(NightPhase.PowerProblem);director.PowerRestored.Value=false;var fuse=Object.FindObjectsByType<NightInteractable>(FindObjectsSortMode.None).First(i=>i.mode==NightInteraction.FusePickup);fuse.Interact(player);Assert.IsTrue(player.HasFuse.Value);var socket=Object.FindObjectsByType<NightInteractable>(FindObjectsSortMode.None).First(i=>i.mode==NightInteraction.FuseSocket);socket.Interact(player);Assert.IsTrue(director.FuseInserted.Value);Assert.IsFalse(player.HasFuse.Value);var breaker=Object.FindObjectsByType<NightInteractable>(FindObjectsSortMode.None).First(i=>i.mode==NightInteraction.Breaker);breaker.Interact(player);yield return null;Assert.IsTrue(director.PowerRestored.Value);Assert.AreEqual((int)NightPhase.WatcherActive,director.Phase.Value);}
  [UnityTest] public IEnumerator ScannerReportsUnknownAndAdvancesObjective(){director.ForcePhaseForTests(NightPhase.WatcherActive);player.ScannerEquipped.Value=true;var exhibit=Object.FindObjectsByType<ScannableExhibit>(FindObjectsSortMode.None).First(e=>e.unknownObjective);exhibit.Interact(player);yield return null;Assert.IsTrue(exhibit.Scanned.Value);Assert.IsTrue(director.UnknownScanned.Value);StringAssert.Contains("отсутствует",player.ScanMessage);}
  [UnityTest] public IEnumerator WatcherFreezesObservedAndApproachesUnobserved(){var watcher=director.watcher;Place(new Vector3(5,1,-6),Quaternion.identity);yield return new WaitForSeconds(.2f);Assert.AreEqual((int)WatcherState.Dormant,watcher.State.Value);director.ForcePhaseForTests(NightPhase.FirstAnomalies);yield return new WaitForSeconds(.2f);Assert.AreEqual((int)WatcherState.Awake,watcher.State.Value);director.ForcePhaseForTests(NightPhase.WatcherActive);Assert.IsTrue(watcher.IsObserved());Vector3 before=watcher.transform.position;yield return new WaitForSeconds(4.5f);Assert.AreEqual(before,watcher.transform.position);player.DebugAim(180);Assert.IsFalse(watcher.IsObserved());yield return new WaitForSeconds(.5f);Assert.Greater(watcher.MoveCount.Value,0);Assert.Less(Vector3.Distance(watcher.transform.position,player.transform.position),Vector3.Distance(before,player.transform.position));player.DebugAim(0);int moves=watcher.MoveCount.Value;yield return new WaitForSeconds(14.5f);Assert.AreEqual(moves,watcher.MoveCount.Value);player.DebugAim(180);yield return new WaitForSeconds(.5f);Assert.Greater(watcher.MoveCount.Value,moves);}
  [UnityTest] public IEnumerator WatcherAttackDropsItemRelocatesAndResets(){director.ForcePhaseForTests(NightPhase.FinalTask);var watcher=director.watcher;var crate=PickupObject.Active.First(p=>!p.heavy);Place(watcher.transform.position+new Vector3(0,1,1.2f),Quaternion.identity);crate.Body.position=player.Eye+Vector3.forward*2;Physics.SyncTransforms();Assert.IsTrue(crate.TryGrab(player));yield return new WaitForSeconds(.4f);Assert.IsFalse(crate.IsHeld);Assert.Greater(player.IncapacitatedUntil.Value,manager.ServerTime.Time);Assert.Greater(Vector3.Distance(player.transform.position,watcher.transform.position),5);}
  [UnityTest] public IEnumerator DestinationIdentityRejectsWrongObject(){var zone=director.shipmentZones[0];var right=PickupObject.Active.First(p=>p.GetComponent<ExhibitIdentity>()?.exhibitId==zone.expectedExhibitId);var wrong=PickupObject.Active.First(p=>p.kind==zone.requiredKind&&p!=right);Assert.IsTrue(zone.Accepts(right));Assert.IsFalse(zone.Accepts(wrong));var id=right.GetComponent<ExhibitIdentity>();string saved=id.destinationId;id.destinationId="wrong";Assert.IsFalse(zone.Accepts(right));id.destinationId=saved;yield return null;}
  [UnityTest] public IEnumerator ObjectiveCratesHaveUniqueMatchingDestinations(){var crates=PickupObject.Active.Where(p=>p.kind=="crate_a"||p.kind=="crate_b").Select(p=>p.GetComponent<ExhibitIdentity>()).OrderBy(i=>i.exhibitId).ToArray();Assert.AreEqual(6,crates.Length);Assert.AreEqual(6,crates.Select(i=>i.exhibitId).Distinct().Count());foreach(var crate in crates){Assert.AreEqual(1,director.shipmentZones.Count(z=>z.expectedExhibitId==crate.exhibitId&&z.Accepts(crate.GetComponent<PickupObject>())));StringAssert.Contains(crate.exhibitId,string.Join("",crate.GetComponentsInChildren<TextMesh>().Select(t=>t.text)));}Assert.IsTrue(director.shipmentZones.All(z=>z.waypoint&&z.waypoint.target&&z.waypoint.roomSize.x>0));yield return null;}
  [UnityTest] public IEnumerator ObjectiveDisplayIsSequential(){Assert.AreEqual("start",director.CurrentStep(shift));StringAssert.Contains("Осмотрите доску",director.ObjectiveText(shift));director.BeginOnboarding();Assert.AreEqual("shipments",director.CurrentStep(shift));StringAssert.Contains("A-01",director.ObjectiveText(shift));StringAssert.DoesNotContain("Осмотрите витрины",director.ObjectiveText(shift));StringAssert.Contains("ТЕКУЩАЯ",director.HistoryText(shift));shift.Crates.Value=director.CrateTarget;Assert.AreEqual("placements",director.CurrentStep(shift));director.Placements.Value=3;Assert.AreEqual("inspect",director.CurrentStep(shift));yield return null;}
  [UnityTest] public IEnumerator PlacementProgressSelectsNextExactCrate(){director.BeginOnboarding();var first=director.CurrentShipmentZone();Assert.AreEqual("A-01",first.expectedExhibitId);var item=PickupObject.Active.First(p=>p.GetComponent<ExhibitIdentity>()?.exhibitId==first.expectedExhibitId);item.Body.position=item.transform.position=first.transform.position;Physics.SyncTransforms();yield return new WaitForSeconds(.35f);Assert.AreEqual(1,shift.Crates.Value);Assert.AreEqual("A-02",director.CurrentShipmentZone().expectedExhibitId);StringAssert.Contains("A-02",director.ObjectiveText(shift));}
  [UnityTest] public IEnumerator ArPlacementIsReachableAndAdvancesNormalFlow(){
   director.BeginOnboarding();foreach(var zone in director.shipmentZones.OrderBy(z=>z.expectedExhibitId).Take(director.CrateTarget)){var crate=PickupObject.Active.First(p=>p.GetComponent<ExhibitIdentity>()?.exhibitId==zone.expectedExhibitId);crate.Release(false);crate.Body.position=crate.transform.position=zone.transform.position;}Physics.SyncTransforms();yield return new WaitForSeconds(.35f);
   Assert.AreEqual("placements",director.CurrentStep(shift));var arZone=director.placementZones.Single(z=>z.requiredKind=="placement_b");var arObject=PickupObject.Active.Single(p=>p.kind=="placement_b");Assert.AreEqual((int)NightPhase.NormalShift,director.Phase.Value);Assert.IsNull(arZone.accessDoor);Assert.IsTrue(arZone.AccessReady(director.Phase.Value));Assert.That(arZone.transform.position.x,Is.InRange(-21f,-7f));Assert.That(arZone.transform.position.z,Is.InRange(13f,23f));Assert.IsTrue(HasPhysicalRoute(arObject.transform.position,arZone.transform.position),"АР-01 must have a walkable route from Receiving to Archaeology before its objective activates.");
   foreach(var zone in director.placementZones){var item=PickupObject.Active.Single(p=>p.kind==zone.requiredKind);item.Release(false);item.Body.position=item.transform.position=zone.transform.position;}Physics.SyncTransforms();yield return new WaitForSeconds(.35f);Assert.AreEqual(3,director.Placements.Value);Assert.AreEqual("inspect",director.CurrentStep(shift));
  }
  [UnityTest] public IEnumerator ObjectiveAccessDependenciesMatchActivationPhases(){
   Assert.IsTrue(director.shipmentZones.All(z=>z.DependencyAllowsPhase((int)NightPhase.NormalShift)));Assert.IsTrue(director.placementZones.All(z=>z.DependencyAllowsPhase((int)NightPhase.NormalShift)));Assert.IsTrue(director.sculptureZone.DependencyAllowsPhase((int)NightPhase.WatcherActive));Assert.IsTrue(director.finalReturnZone.DependencyAllowsPhase((int)NightPhase.FinalTask));
   Assert.AreSame(director.restrictedDoor,director.archiveReturnZone.accessDoor);Assert.IsFalse(director.archiveReturnZone.AccessReady((int)NightPhase.NormalShift));Assert.IsFalse(director.restrictedDoor.CanInteract(player));director.Advance(NightPhase.RestrictedArea);yield return null;Assert.IsFalse(director.restrictedDoor.Locked.Value);Assert.IsTrue(director.archiveReturnZone.AccessReady(director.Phase.Value));Assert.IsTrue(director.restrictedDoor.CanInteract(player));
   var scanner=Object.FindFirstObjectByType<InventoryScanner>();Assert.That(scanner.transform.position.x,Is.InRange(-32f,-22f));Assert.That(scanner.transform.position.z,Is.InRange(-23f,-13f));var fuses=Object.FindObjectsByType<NightInteractable>(FindObjectsSortMode.None).Where(i=>i.mode==NightInteraction.FusePickup).ToArray();Assert.IsTrue(fuses.Any(f=>f.transform.position.x>=-32f&&f.transform.position.x<=-22f&&f.transform.position.z>=-12f&&f.transform.position.z<=12f));
  }
  [UnityTest] public IEnumerator CorrectHeldCrateGuidesToRoomAndHighlightsOnlyMatchingSlot(){director.BeginOnboarding();var zone=director.CurrentShipmentZone();var right=PickupObject.Active.First(p=>p.GetComponent<ExhibitIdentity>()?.exhibitId==zone.expectedExhibitId);var wrong=PickupObject.Active.First(p=>p.kind==zone.requiredKind&&p!=right);Place(right.transform.position+Vector3.back*2,Quaternion.identity);right.Body.position=player.Eye+Vector3.forward*2;Physics.SyncTransforms();Assert.IsTrue(right.TryGrab(player));yield return new WaitForSeconds(.2f);Assert.IsTrue(zone.marker.activeSelf);Assert.IsTrue(zone.waypoint.GetComponent<Renderer>().enabled);Assert.IsTrue(director.shipmentZones.Where(z=>z!=zone).All(z=>!z.marker.activeSelf));StringAssert.Contains(zone.expectedExhibitId,zone.WrongFeedback(wrong));Place(new Vector3(zone.waypoint.roomCenter.x,1,zone.waypoint.roomCenter.y),Quaternion.identity);yield return new WaitForSeconds(.2f);Assert.IsFalse(zone.waypoint.GetComponent<Renderer>().enabled);right.Release(false);}
  [UnityTest] public IEnumerator SoloNormalWorkUnlocksFirstAnomalies(){director.BeginOnboarding();foreach(var zone in director.shipmentZones.OrderBy(z=>z.expectedExhibitId).Take(director.CrateTarget)){var item=PickupObject.Active.First(p=>p.GetComponent<ExhibitIdentity>()?.exhibitId==zone.expectedExhibitId);item.Release(false);item.Body.position=item.transform.position=zone.transform.position;}foreach(var zone in director.placementZones){var item=PickupObject.Active.First(p=>p.kind==zone.requiredKind);item.Body.position=item.transform.position=zone.transform.position;}foreach(var display in Object.FindObjectsByType<DisplayCase>(FindObjectsSortMode.None))display.Interact(player);Physics.SyncTransforms();yield return new WaitForSeconds(.5f);Assert.AreEqual((int)NightPhase.FirstAnomalies,director.Phase.Value);Assert.IsTrue(director.anomalies.All(a=>a.Revealed.Value));}
  [UnityTest] public IEnumerator FlashlightTogglesWithFAndSurvivesOnboardingReset(){var settings=InputSystem.settings;var background=settings.backgroundBehavior;settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;var keyboard=InputSystem.AddDevice<Keyboard>();
#if UNITY_EDITOR
   var editorBehavior=settings.editorInputBehaviorInPlayMode;settings.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;
#endif
   try{player.SetPause(false);Assert.IsNotNull(player.flashlight);Assert.IsFalse(player.FlashlightOn.Value);InputSystem.QueueStateEvent(keyboard,new KeyboardState(Key.F));yield return new WaitForSeconds(.15f);Assert.IsTrue(player.FlashlightOn.Value);Assert.IsTrue(player.flashlight.enabled);InputSystem.QueueStateEvent(keyboard,new KeyboardState());yield return null;InputSystem.QueueStateEvent(keyboard,new KeyboardState(Key.F));yield return new WaitForSeconds(.15f);Assert.IsFalse(player.FlashlightOn.Value);Assert.IsFalse(player.flashlight.enabled);InputSystem.QueueStateEvent(keyboard,new KeyboardState());yield return null;InputSystem.QueueStateEvent(keyboard,new KeyboardState(Key.F));yield return new WaitForSeconds(.15f);Assert.IsTrue(player.FlashlightOn.Value);director.ResetOnboarding();yield return null;Assert.IsNotNull(player.flashlight);Assert.IsTrue(player.FlashlightOn.Value);}finally{InputSystem.RemoveDevice(keyboard);settings.backgroundBehavior=background;
#if UNITY_EDITOR
   settings.editorInputBehaviorInPlayMode=editorBehavior;
#endif
  }}
 }
}
